name: Android Build

on: push

jobs:
  build:
    name: Install MSBuild
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Check MSBuild
        run: MSBuild /help
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Restore
        run: nuget restore GenericMobileApp/GenericMobileApp.sln
      - name: Build
        run: msbuild GenericMobileApp/GenericMobileApp.sln

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
