name: Install MSBuild Windows

on: push

jobs:
  build:
    name: Install MSBuild
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Check MSBuild
        run: MSBuild /help
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Restore
        run: nuget restore GenericMobileApp/GenericMobileApp.sln
      - name: Build
        run: msbuild GenericMobileApp/GenericMobileApp.sln
